### ISSUE TITLE
Having issue in npm install

### ISSUE THREAD

**Issue by jaber-mtl** [muhamed-didovic/laradown#1]
@muhamed-didovic 

![image](https://github.com/muhamed-didovic/laradown/assets/103347464/8867fda1-bf12-4089-a00d-96d9cc43fb53)

**Comment by muhamed-didovic** [comment]
@jaber-mtl, pushed new version, please verify, you almost use all my scrapers :)

**Comment by JaberWiki** [comment]
another error @muhamed-didovic 
![image](https://github.com/muhamed-didovic/laradown/assets/55241455/9b6ac0e2-fe29-483d-8855-785823a03eb8)

**Comment by muhamed-didovic** [comment]
@jaber-mtl pushed something, pull new version and try

**Comment by JaberWiki** [comment]
> @jaber-mtl pushed something, pull new version and try

still @muhamed-didovic 
![image](https://github.com/muhamed-didovic/laradown/assets/55241455/20bd739a-d32e-4d32-829e-8f0cfda83724)

![image](https://github.com/muhamed-didovic/laradown/assets/55241455/49085d25-0080-4cbf-824c-a8325c10cd00)

**Comment by JaberWiki** [comment]
maybe getting the error from this code @muhamed-didovic 
![image](https://github.com/muhamed-didovic/laradown/assets/55241455/8a3d2bad-3dee-4b2a-9ae4-898a2ceb75c0)

**Comment by muhamed-didovic** [comment]
pushed new version, please pull, if it fails there is also debug so send screenshot

**Comment by jaber-mtl** [comment]
still same error @muhamed-didovic 

![image](https://github.com/muhamed-didovic/laradown/assets/103347464/9f4ae8c3-882d-44a5-b948-e6f77b333fd0)

**Comment by muhamed-didovic** [comment]
I see that you run command from 'lib' folder, can you check is there a 'json' folder in root of the project?

**Comment by muhamed-didovic** [comment]
pushed something new, please pull and verify

**Comment by jaber-mtl** [comment]
> pushed something new, please pull and verify

@muhamed-didovic 
After commenting this line, files are downloading but the file names add some random text after the main file name.

![image](https://github.com/muhamed-didovic/laradown/assets/103347464/9d54017d-d821-482e-be6a-c6b6804f7c58)

**Comment by JaberWiki** [comment]
@muhamed-didovic  why its adding unnecessary words with the video file name?
![image](https://github.com/muhamed-didovic/laradown/assets/55241455/1eff0092-89a2-4474-88ab-9eef3fdc9481)
